### ISSUE TITLE
Cannot use hotkey Ctrl + C or Ctrl + V when edit shared files Nextcloud

### ISSUE THREAD

**Issue by classical** [btactic-oo/unlimited-onlyoffice-package-builder#2]
When I edit a shared files from another user, even thought with full rights , I cannot use hotkeys Ctrl + C (copy content within that sheet) and Ctrl + V (paste to another cell within that sheet also). I can click the button Copy and Paste to do that function but cannot use hotkeys.
Please help me to solve this problem

**Comment by adriangibanelbtactic** [comment]
This is not an OnlyOffice forum.

Please reopen if this behaviour is different to the one that upstream OnlyOffice packages provide.

Closing the issue.
