### ISSUE TITLE
new version?

### ISSUE THREAD

**Issue by razerrazer** [btactic-oo/unlimited-onlyoffice-package-builder#3]
Hi,

How to for example get the latest version of OO?

**Comment by adriangibanelbtactic** [comment]
> Hi,
> 
> How to for example get the latest version of OO?

Here you are: https://github.com/btactic-oo/unlimited-onlyoffice-package-builder/blob/main/onlyoffice-no-limits-2024-06.md .

Maybe you should start from the [Development log section](https://github.com/btactic-oo/unlimited-onlyoffice-package-builder/blob/main/onlyoffice-no-limits-2024-05.md#development-log) and then read the full document again.

Good luck!

**Comment by adriangibanelbtactic** [comment]
https://github.com/btactic-oo/unlimited-onlyoffice-package-builder/commit/20e4f288c05b9d5a7f9861f1173283e584205eb7 closes this issue.
